In [2]:
import pandas as pd
import numpy as np

In [2]:
df_rev = pd.read_json('Video_Games.json.gz', orient='columns',lines=True,nrows=200000)
df_rev["reviewTime"] = pd.to_datetime(df_rev["reviewTime"])
df_rev.head()

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,vote,style,image
0,1,True,2014-06-09,A21ROB4YDOZA5P,0439381673,Mary M. Clark,I used to play this game years ago and loved i...,Did not like this,1402272000,NaN,NaN,NaN
1,3,True,2014-05-10,A3TNZ2Q5E7HTHD,0439381673,Sarabatya,The game itself worked great but the story lin...,Almost Perfect,1399680000,NaN,NaN,NaN
2,4,True,2014-02-07,A1OKRM3QFEATQO,0439381673,Amazon Customer,I had to learn the hard way after ordering thi...,DOES NOT WORK WITH MAC OS unless it is 10.3 or...,1391731200,15,NaN,NaN
3,1,True,2014-02-07,A2XO1JFCNEYV3T,0439381673,ColoradoPartyof5,The product description should state this clea...,does not work on Mac OSX,1391731200,11,NaN,NaN
4,4,True,2014-01-16,A19WLPIRHD15TH,0439381673,Karen Robinson,I would recommend this learning game for anyon...,Roughing it,1389830400,NaN,NaN,NaN

In [3]:
import re
def cleaning(text):
    text = re.sub('[^0-9A-Za-z]+',' ',text)
    text= re.sub('(?<!\w)\d+','',text)
    text=re.sub('-(?!\w)|(?<!\w)-','',text)
    text=text.lower()
    text=re.sub(' +',' ',text)
    return text
df_rev["reviewText"]=df_rev["reviewText"].astype(str)
df_rev["summary"]=df_rev["summary"].astype(str)
df_rev["reviewText"]=df_rev["reviewText"].apply(cleaning)
df_rev["summary"]=df_rev["summary"].apply(cleaning)

In [4]:
df_rev.head()

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,vote,style,image
0,1,True,2014-06-09,A21ROB4YDOZA5P,0439381673,Mary M. Clark,i used to play this game years ago and loved i...,did not like this,1402272000,NaN,NaN,NaN
1,3,True,2014-05-10,A3TNZ2Q5E7HTHD,0439381673,Sarabatya,the game itself worked great but the story lin...,almost perfect,1399680000,NaN,NaN,NaN
2,4,True,2014-02-07,A1OKRM3QFEATQO,0439381673,Amazon Customer,i had to learn the hard way after ordering thi...,does not work with mac os unless it is or less...,1391731200,15,NaN,NaN
3,1,True,2014-02-07,A2XO1JFCNEYV3T,0439381673,ColoradoPartyof5,the product description should state this clea...,does not work on mac osx,1391731200,11,NaN,NaN
4,4,True,2014-01-16,A19WLPIRHD15TH,0439381673,Karen Robinson,i would recommend this learning game for anyon...,roughing it,1389830400,NaN,NaN,NaN

In [5]:
df_rev["review"] = df_rev['reviewText'].astype(str) +" "+ df_rev["summary"]
df_rev=df_rev.drop(['unixReviewTime','vote','style','image'],axis=1)
df_rev

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,review
0,1,True,2014-06-09,A21ROB4YDOZA5P,0439381673,Mary M. Clark,i used to play this game years ago and loved i...,did not like this,i used to play this game years ago and loved i...
1,3,True,2014-05-10,A3TNZ2Q5E7HTHD,0439381673,Sarabatya,the game itself worked great but the story lin...,almost perfect,the game itself worked great but the story lin...
2,4,True,2014-02-07,A1OKRM3QFEATQO,0439381673,Amazon Customer,i had to learn the hard way after ordering thi...,does not work with mac os unless it is or less...,i had to learn the hard way after ordering thi...
3,1,True,2014-02-07,A2XO1JFCNEYV3T,0439381673,ColoradoPartyof5,the product description should state this clea...,does not work on mac osx,the product description should state this clea...
4,4,True,2014-01-16,A19WLPIRHD15TH,0439381673,Karen Robinson,i would recommend this learning game for anyon...,roughing it,i would recommend this learning game for anyon...
...,...,...,...,...,...,...,...,...,...
199995,5,True,2013-01-18,A1Z7DBXPWSN0FS,B00029QOQ8,Kindle Customer,i had the original roller coaster tycoon a lon...,worth it,i had the original roller coaster tycoon a lon...
199996,5,True,2013-01-14,A1AJPCJEVJLVA6,B00029QOQ8,Andy,its the old roller coaster tycoon game and it ...,just like i remembered,its the old roller coaster tycoon game and it ...
199997,4,True,2013-01-13,A2XVB8X8HGEGMU,B00029QOQ8,Jake,have not played this game since i was just a y...,fun fun fun,have not played this game since i was just a y...
199998,4,False,2013-01-08,A8UR3PE9MPC9U,B00029QOQ8,A_Belmont,i wish they d make a fourth one of these this ...,a classic,i wish they d make a fourth one of these this ...
199999,5,True,2013-01-08,A3BSY4D0RWKIG7,B00029QOQ8,J. Emerson,originally released in for xp it works perfect...,classic game loads of fun,originally released in for xp it works perfect...

In [6]:
df_rev["Number_of_Words_in_review"] = df_rev["review"].apply(lambda n: len(n.split()))

df_rev

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,review,Number_of_Words_in_review
0,1,True,2014-06-09,A21ROB4YDOZA5P,0439381673,Mary M. Clark,i used to play this game years ago and loved i...,did not like this,i used to play this game years ago and loved i...,33
1,3,True,2014-05-10,A3TNZ2Q5E7HTHD,0439381673,Sarabatya,the game itself worked great but the story lin...,almost perfect,the game itself worked great but the story lin...,29
2,4,True,2014-02-07,A1OKRM3QFEATQO,0439381673,Amazon Customer,i had to learn the hard way after ordering thi...,does not work with mac os unless it is or less...,i had to learn the hard way after ordering thi...,90
3,1,True,2014-02-07,A2XO1JFCNEYV3T,0439381673,ColoradoPartyof5,the product description should state this clea...,does not work on mac osx,the product description should state this clea...,33
4,4,True,2014-01-16,A19WLPIRHD15TH,0439381673,Karen Robinson,i would recommend this learning game for anyon...,roughing it,i would recommend this learning game for anyon...,22
...,...,...,...,...,...,...,...,...,...,...
199995,5,True,2013-01-18,A1Z7DBXPWSN0FS,B00029QOQ8,Kindle Customer,i had the original roller coaster tycoon a lon...,worth it,i had the original roller coaster tycoon a lon...,58
199996,5,True,2013-01-14,A1AJPCJEVJLVA6,B00029QOQ8,Andy,its the old roller coaster tycoon game and it ...,just like i remembered,its the old roller coaster tycoon game and it ...,25
199997,4,True,2013-01-13,A2XVB8X8HGEGMU,B00029QOQ8,Jake,have not played this game since i was just a y...,fun fun fun,have not played this game since i was just a y...,24
199998,4,False,2013-01-08,A8UR3PE9MPC9U,B00029QOQ8,A_Belmont,i wish they d make a fourth one of these this ...,a classic,i wish they d make a fourth one of these this ...,105
199999,5,True,2013-01-08,A3BSY4D0RWKIG7,B00029QOQ8,J. Emerson,originally released in for xp it works perfect...,classic game loads of fun,originally released in for xp it works perfect...,78

In [7]:
df_rev.isnull().sum()

overall                       0
verified                      0
reviewTime                    0
reviewerID                    0
asin                          0
reviewerName                 10
reviewText                    0
summary                       0
review                        0
Number_of_Words_in_review     0
dtype: int64

In [8]:
df_rev["reviewerName"].fillna(df_rev["reviewerName"].mode()[0], inplace=True)

In [9]:
df_rev.isnull().sum()

overall                      0
verified                     0
reviewTime                   0
reviewerID                   0
asin                         0
reviewerName                 0
reviewText                   0
summary                      0
review                       0
Number_of_Words_in_review    0
dtype: int64

In [10]:
df_rev['Sentiment']=df_rev['overall']
df_rev['Sentiment'] = df_rev['Sentiment'].replace(5,'positive')
df_rev['Sentiment'] = df_rev['Sentiment'].replace(4,'positive')

df_rev['Sentiment'] = df_rev['Sentiment'].replace(2,'negetive')
df_rev['Sentiment'] = df_rev['Sentiment'].replace(1,'negetive')

df_rev['Sentiment'] = df_rev['Sentiment'].replace(3,'neutral')

In [11]:
df_rev

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,review,Number_of_Words_in_review,Sentiment
0,1,True,2014-06-09,A21ROB4YDOZA5P,0439381673,Mary M. Clark,i used to play this game years ago and loved i...,did not like this,i used to play this game years ago and loved i...,33,negetive
1,3,True,2014-05-10,A3TNZ2Q5E7HTHD,0439381673,Sarabatya,the game itself worked great but the story lin...,almost perfect,the game itself worked great but the story lin...,29,neutral
2,4,True,2014-02-07,A1OKRM3QFEATQO,0439381673,Amazon Customer,i had to learn the hard way after ordering thi...,does not work with mac os unless it is or less...,i had to learn the hard way after ordering thi...,90,positive
3,1,True,2014-02-07,A2XO1JFCNEYV3T,0439381673,ColoradoPartyof5,the product description should state this clea...,does not work on mac osx,the product description should state this clea...,33,negetive
4,4,True,2014-01-16,A19WLPIRHD15TH,0439381673,Karen Robinson,i would recommend this learning game for anyon...,roughing it,i would recommend this learning game for anyon...,22,positive
...,...,...,...,...,...,...,...,...,...,...,...
199995,5,True,2013-01-18,A1Z7DBXPWSN0FS,B00029QOQ8,Kindle Customer,i had the original roller coaster tycoon a lon...,worth it,i had the original roller coaster tycoon a lon...,58,positive
199996,5,True,2013-01-14,A1AJPCJEVJLVA6,B00029QOQ8,Andy,its the old roller coaster tycoon game and it ...,just like i remembered,its the old roller coaster tycoon game and it ...,25,positive
199997,4,True,2013-01-13,A2XVB8X8HGEGMU,B00029QOQ8,Jake,have not played this game since i was just a y...,fun fun fun,have not played this game since i was just a y...,24,positive
199998,4,False,2013-01-08,A8UR3PE9MPC9U,B00029QOQ8,A_Belmont,i wish they d make a fourth one of these this ...,a classic,i wish they d make a fourth one of these this ...,105,positive
199999,5,True,2013-01-08,A3BSY4D0RWKIG7,B00029QOQ8,J. Emerson,originally released in for xp it works perfect...,classic game loads of fun,originally released in for xp it works perfect...,78,positive

# Meta

In [146]:
df_meta = pd.read_json('meta_Video_Games.json.gz', orient='columns',lines=True)

In [147]:
df_meta['category']=df_meta['category'].apply(lambda x: ', '.join(map(str, x)))
df_meta['description']=df_meta['description'].apply(lambda x: ', '.join(map(str, x)))
df_meta['also_buy']=df_meta['also_buy'].apply(lambda x: ', '.join(map(str, x)))
df_meta['feature']=df_meta['feature'].apply(lambda x: ', '.join(map(str, x)))
df_meta['rank']=df_meta['rank'].apply(lambda x: ', '.join(map(str, x)))
df_meta['also_view']=df_meta['also_view'].apply(lambda x: ', '.join(map(str, x)))
df_meta['imageURL']=df_meta['imageURL'].apply(lambda x: ', '.join(map(str, x)))

In [148]:
import re
def cleaning(text):
    text = re.sub('[^0-9A-Za-z]+',' ',text)
    text = re.sub('span',' ',text)
    text = re.sub('\n',' ',text)
    text = text.lower()
    return text

df_meta['category']=df_meta['category'].apply(cleaning)
df_meta['description']=df_meta['description'].apply(cleaning)

In [149]:
import re
def cleaning(text):
    text = re.sub('[^0-9A-Za-z]+',' ',text)
    text = re.sub('by',' ',text)    
    text = text.lower()
    return text
df_meta['brand']=df_meta['brand'].apply(cleaning)

In [150]:
df_meta['rank'][43]

'1, 7, ,, 2, 0, 9, ,, 5, 1, 8,  , i, n,  , B, o, o, k, s,  , ('

In [151]:
import re
def cleaning(text):
    text = text.lower()
    text = re.sub(r'\si.*',' ',text)
    text = re.sub('>#',' ',text) 
    text = re.sub(r':.*',' ',text)
    text = re.sub(r'\ss.*',' ',text)
    text = re.sub(r'\sp.*',' ',text)
    text = re.sub(r'[\sa-z.*]',' ',text)
    text = re.sub(',',' ',text)
    text = re.sub(r"\s", "", text)
    
    return text
df_meta['rank']=df_meta['rank'].apply(cleaning)

In [152]:
df_meta.drop(columns=['tech1','fit','tech2','similar_item','date','details','imageURLHighRes','also_buy','also_view','feature','price'],inplace=True)

In [153]:
df_meta=df_meta.mask(df_meta == '')

In [154]:
df_meta['rank'][52242]

nan

In [155]:
#df_meta['rank'] = df_meta['rank'].astype(int)
df_meta['rank'] = pd.to_numeric(df_meta['rank'])

In [156]:
df_meta.isnull().sum()

category        2425
description    10174
title             11
brand           4027
rank            4501
main_cat         120
asin               0
imageURL       22863
dtype: int64

In [157]:
df_meta.dtypes

category        object
description     object
title           object
brand           object
rank           float64
main_cat        object
asin            object
imageURL        object
dtype: object

In [158]:
df_meta["category"].fillna(df_meta["category"].mode()[0], inplace=True)
df_meta["description"].fillna(df_meta["description"].mode()[0], inplace=True)
df_meta["brand"].fillna(df_meta["brand"].mode()[0], inplace=True)
df_meta["rank"].fillna(df_meta["rank"].mean(), inplace=True)
df_meta["title"].fillna(df_meta["title"].mode()[0], inplace=True)
df_meta["main_cat"].fillna(df_meta["main_cat"].mode()[0], inplace=True)

In [159]:
df_meta.isnull().sum()

category           0
description        0
title              0
brand              0
rank               0
main_cat           0
asin               0
imageURL       22863
dtype: int64

In [160]:
df_meta['image_uploaded']=np.nan
df_meta['imageURL']=df_meta['imageURL'].astype(str)
a=0

for i in df_meta['imageURL']:
    z=re.match("^http",i, re.IGNORECASE)
    if bool(z) == True:
        df_meta['image_uploaded'][a]='yes'
    else:
        df_meta['image_uploaded'][a]='no'
    a=a+1

C:\Users\mahbp\AppData\Local\Temp\ipykernel_24452\1043129204.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_meta['image_uploaded'][a]='yes'

In [161]:
df_meta.drop(columns=['imageURL'],inplace=True)

In [162]:
merged = pd.merge(df_rev,df_meta,on=['asin'], how='inner')
merged.shape

(392782, 18)

In [163]:
merged.drop_duplicates(subset=["reviewText","summary"],keep='first', inplace=True)

In [164]:
merged.shape

(193365, 18)

In [165]:
merged.to_csv("Final_Video_Games.csv",index=False)

In [3]:
df12=pd.read_csv("Final_Video_Games.csv")
df12

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,review,Number_of_Words_in_review,Sentiment,category,description,title,brand,rank,main_cat,image_uploaded
0,1,True,2014-06-09,A21ROB4YDOZA5P,0439381673,Mary M. Clark,i used to play this game years ago and loved i...,did not like this,i used to play this game years ago and loved i...,33,negetive,video games pc games,oregon trail 5th edition jewel case create you...,BRAND NEW Learning Company Oregon Trail 5th Ed...,learning company,5927.0,Video Games,yes
1,3,True,2014-05-10,A3TNZ2Q5E7HTHD,0439381673,Sarabatya,the game itself worked great but the story lin...,almost perfect,the game itself worked great but the story lin...,29,neutral,video games pc games,oregon trail 5th edition jewel case create you...,BRAND NEW Learning Company Oregon Trail 5th Ed...,learning company,5927.0,Video Games,yes
2,4,True,2014-02-07,A1OKRM3QFEATQO,0439381673,Amazon Customer,i had to learn the hard way after ordering thi...,does not work with mac os unless it is or less...,i had to learn the hard way after ordering thi...,90,positive,video games pc games,oregon trail 5th edition jewel case create you...,BRAND NEW Learning Company Oregon Trail 5th Ed...,learning company,5927.0,Video Games,yes
3,1,True,2014-02-07,A2XO1JFCNEYV3T,0439381673,ColoradoPartyof5,the product description should state this clea...,does not work on mac osx,the product description should state this clea...,33,negetive,video games pc games,oregon trail 5th edition jewel case create you...,BRAND NEW Learning Company Oregon Trail 5th Ed...,learning company,5927.0,Video Games,yes
4,4,True,2014-01-16,A19WLPIRHD15TH,0439381673,Karen Robinson,i would recommend this learning game for anyon...,roughing it,i would recommend this learning game for anyon...,22,positive,video games pc games,oregon trail 5th edition jewel case create you...,BRAND NEW Learning Company Oregon Trail 5th Ed...,learning company,5927.0,Video Games,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193360,1,False,2004-12-03,A2QRTM0CO9GU0P,B00029QR8I,Roy Hobbs,i received the game with anticipation one day ...,what a disappointment,i received the game with anticipation one day ...,87,negetive,video games pc games,sid meier s pirates live the life originally r...,Sid Meier's Pirates! (Live the Life),2k,37609.0,Video Games,yes
193361,5,False,2004-12-03,A2DQBIBHLOXC46,B00029QR8I,Write U. Arre,sid meier s pirates is the most addictive game...,why you ll lose your job your wife and your life,sid meier s pirates is the most addictive game...,551,positive,video games pc games,sid meier s pirates live the life originally r...,Sid Meier's Pirates! (Live the Life),2k,37609.0,Video Games,yes
193362,1,False,2004-12-03,A37LFNP87PU4DO,B00029QR8I,"Rauol Duke, Jr.",add me to the list of those who simply could n...,another frustrated customer,add me to the list of those who simply could n...,85,negetive,video games pc games,sid meier s pirates live the life originally r...,Sid Meier's Pirates! (Live the Life),2k,37609.0,Video Games,yes
193363,1,True,2004-12-01,AJ2JGHGVB339V,B00029QR8I,JB,i really think the title says it all its a ter...,buggy rushed sloppy and terrible support,i really think the title says it all its a ter...,65,negetive,video games pc games,sid meier s pirates live the life originally r...,Sid Meier's Pirates! (Live the Life),2k,37609.0,Video Games,yes
193364,1,False,2004-12-01,AINT9RKF94C0T,B00029QR8I,Amazon Customer,the game is great but it does not work on any ...,beware does not work on any intel video chipsets,the game is great but it does not work on any ...,104,negetive,video games pc games,sid meier s pirates live the life originally r...,Sid Meier's Pirates! (Live the Life),2k,37609.0,Video Games,yes