Meta Data Set

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [1]:
# to read the data
import os
import json
import gzip

from urllib.request import urlopen

# dataframe and series 
import pandas as pd
import numpy as np

In [2]:
# getting data from json.gz file

df_data = []
with gzip.open('/content/drive/MyDrive/folder/meta_Toys_and_Games.json.gz') as data:
    for i in data:
        df_data.append(json.loads(i.strip()))

In [3]:

# to see the length of the data, it means total number of reviews also
print(len(df_data))

# to see the first row of the list
print(df_data[0])

633883
{'category': ['Toys & Games', 'Puzzles', 'Jigsaw Puzzles'], 'tech1': '', 'description': ["Three Dr. Suess' Puzzles: Green Eggs and Ham, Favorite Friends, and One Fish Two Fish Red Fish Blue Fish"], 'fit': '', 'title': 'Dr. Suess 19163 Dr. Seuss Puzzle 3 Pack Bundle', 'also_buy': [], 'tech2': '', 'brand': 'Dr. Seuss', 'feature': ['Three giant floor puzzles', 'Includes: Dr. Suess Green Eggs and Ham, Favorite Friends, and One Fish Two Fish Blue Fish', 'Each puzzle has 48 pieces', 'Ages 3 and up'], 'rank': ['>#2,230,717 in Toys & Games (See Top 100 in Toys & Games)', '>#57,419 in Toys & Games > Puzzles > Jigsaw Puzzles'], 'also_view': [], 'main_cat': 'Toys & Games', 'similar_item': '', 'date': '', 'price': '', 'asin': '0000191639', 'imageURL': ['https://images-na.ssl-images-amazon.com/images/I/51rn8TxbcoL._SS40_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/51j1Fep1niL._SS40_.jpg'], 'imageURLHighRes': ['https://images-na.ssl-images-amazon.com/images/I/51rn8TxbcoL.jpg', 'https://images-na.ssl-images-amazon.com/images/I/51j1Fep1niL.jpg']}

In [5]:
df_meta = pd.DataFrame.from_dict(df_data) # convert dictionary to dataframe

In [6]:
df_meta.head()

,category,tech1,description,fit,title,also_buy,tech2,brand,feature,rank,also_view,main_cat,similar_item,date,price,asin,imageURL,imageURLHighRes,details
0,"[Toys & Games, Puzzles, Jigsaw Puzzles]",,"[Three Dr. Suess' Puzzles: Green Eggs and Ham,...",,Dr. Suess 19163 Dr. Seuss Puzzle 3 Pack Bundle,[],,Dr. Seuss,"[Three giant floor puzzles, Includes: Dr. Sues...","[>#2,230,717 in Toys & Games (See Top 100 in T...",[],Toys & Games,,,,0000191639,[https://images-na.ssl-images-amazon.com/image...,[https://images-na.ssl-images-amazon.com/image...,NaN
1,[],,[<b>Prepare to be Afraid!</b><br /><br />The B...,,Pathfinder: Book of Beasts - Legendary Foes,[],,Pathfinder Roleplaying Jon Brazer Productions,[],"[>#2,294,535 in Toys & Games (See Top 100 in T...",[],Toys & Games,,,.a-box-inner{background-color:#fff}#alohaBuyBo...,0004950763,[],[],NaN
2,[],,[],,Nursery Rhymes Felt Book,[],,Betty Lukens,[],"[>#2,871,983 in Toys & Games (See Top 100 in T...",[],Toys & Games,,,.a-box-inner{background-color:#fff}#alohaBuyBo...,0005069491,[],[],NaN
3,"[Toys & Games, Games, Card Games]",,[Blitz Vintage Card Game],,Dutch Blitz Card Game,[B00WIIPQEC],,Dutch Blitz Games Co,[],"[>#376,337 in Toys & Games (See Top 100 in Toy...","[B000BBU0KS, B00NQQTZ5G, B00WIIPQEC, B001VIWAO...",Toys & Games,"class=""a-bordered a-horizontal-stripes a-spa...",,$24.95,0004983289,[],[],NaN
4,[],,"[Marvel SuperHeroes themed ""magic ink"" colorin...",,Magic Pen Painting (Marvel Super Heroes),"[B009SB7TI8, B009SB8Z1I]",,Lee Publications,[],"[>#934,954 in Toys & Games (See Top 100 in Toy...",[],Toys & Games,,,$4.92,0006466222,[],[],NaN

In [7]:
df_meta.shape

(633883, 19)

In [8]:
df_meta.columns

Index(['category', 'tech1', 'description', 'fit', 'title', 'also_buy', 'tech2',
       'brand', 'feature', 'rank', 'also_view', 'main_cat', 'similar_item',
       'date', 'price', 'asin', 'imageURL', 'imageURLHighRes', 'details'],
      dtype='object')

In [9]:
df_meta['category']=df_meta['category'].apply(lambda x: ', '.join(map(str, x)))
df_meta['description']=df_meta['description'].apply(lambda x: ', '.join(map(str, x)))
df_meta['also_buy']=df_meta['also_buy'].apply(lambda x: ', '.join(map(str, x)))
df_meta['feature']=df_meta['feature'].apply(lambda x: ', '.join(map(str, x)))
df_meta['rank']=df_meta['rank'].apply(lambda x: ', '.join(map(str, x)))
df_meta['also_view']=df_meta['also_view'].apply(lambda x: ', '.join(map(str, x)))
df_meta['imageURL']=df_meta['imageURL'].apply(lambda x: ', '.join(map(str, x)))

In [10]:
import re
def cleaning(text):
    text = re.sub('[^0-9A-Za-z]+',' ',text)
    text = re.sub('span',' ',text)
    text = re.sub('\n',' ',text)
    text = text.lower()
    return text

df_meta['category']=df_meta['category'].apply(cleaning)
df_meta['description']=df_meta['description'].apply(cleaning)

In [11]:
import re
def cleaning(text):
    text = re.sub('[^0-9A-Za-z]+',' ',text)
    text = re.sub('by',' ',text)    
    text = text.lower()
    return text
df_meta['brand']=df_meta['brand'].apply(cleaning)

In [12]:
import re
def cleaning(text):
    text = text.lower()
    text = re.sub(r'\si.*',' ',text)
    text = re.sub('>#',' ',text) 
    text = re.sub(r':.*',' ',text)
    text = re.sub(r'\ss.*',' ',text)
    text = re.sub(r'\sp.*',' ',text)
    text = re.sub(r'[\sa-z.*]',' ',text)
    text = re.sub(',',' ',text)
    text = re.sub(r"\s", "", text)
    
    return text
df_meta['rank']=df_meta['rank'].apply(cleaning)

In [13]:
df_meta.drop(columns=['tech1','fit','tech2','similar_item','date','details','imageURLHighRes','also_buy','also_view','feature','price'],inplace=True)

In [14]:
df_meta.head()

,category,description,title,brand,rank,main_cat,asin,imageURL
0,toys games puzzles jigsaw puzzles,three dr suess puzzles green eggs and ham favo...,Dr. Suess 19163 Dr. Seuss Puzzle 3 Pack Bundle,dr seuss,2230717,Toys & Games,0000191639,https://images-na.ssl-images-amazon.com/images...
1,,b prepare to be afraid b br br the book of be...,Pathfinder: Book of Beasts - Legendary Foes,pathfinder roleplaying jon brazer productions,2294535,Toys & Games,0004950763,
2,,,Nursery Rhymes Felt Book,betty lukens,2871983,Toys & Games,0005069491,
3,toys games games card games,blitz vintage card game,Dutch Blitz Card Game,dutch blitz games co,376337,Toys & Games,0004983289,
4,,marvel superheroes themed magic ink coloring b...,Magic Pen Painting (Marvel Super Heroes),lee publications,934954,Toys & Games,0006466222,

In [15]:
df_meta['rank'].unique()

array(['2230717', '2294535', '2871983', ..., '482069', '401674', '652169'],
      dtype=object)

In [16]:
df_meta=df_meta.mask(df_meta == '')

In [18]:
df_meta

,category,description,title,brand,rank,main_cat,asin,imageURL
0,toys games puzzles jigsaw puzzles,three dr suess puzzles green eggs and ham favo...,Dr. Suess 19163 Dr. Seuss Puzzle 3 Pack Bundle,dr seuss,2230717,Toys & Games,0000191639,https://images-na.ssl-images-amazon.com/images...
1,NaN,b prepare to be afraid b br br the book of be...,Pathfinder: Book of Beasts - Legendary Foes,pathfinder roleplaying jon brazer productions,2294535,Toys & Games,0004950763,NaN
2,NaN,NaN,Nursery Rhymes Felt Book,betty lukens,2871983,Toys & Games,0005069491,NaN
3,toys games games card games,blitz vintage card game,Dutch Blitz Card Game,dutch blitz games co,376337,Toys & Games,0004983289,NaN
4,NaN,marvel superheroes themed magic ink coloring b...,Magic Pen Painting (Marvel Super Heroes),lee publications,934954,Toys & Games,0006466222,NaN
...,...,...,...,...,...,...,...,...
633878,toys games hobbies remote app controlled vehic...,NaN,Geilienergy 6V 2000mAh NiMH RX Battery Packs w...,geilienergy,401674,Tools & Home Improvement,B01HJDFWDK,https://images-na.ssl-images-amazon.com/images...
633879,toys games sports outdoor play pools water fun...,suitable for children ages 6 36 months old br ...,Micord Baby Float Toddler Swimming Inflatable ...,micord,652169,Toys & Games,B01HJDGVFS,https://images-na.ssl-images-amazon.com/images...
633880,toys games sports outdoor play pools water fun,just choose it make you forget all the trouble...,"Premium Swimming Pool Float Hammock, Inflatabl...",wavepy,253066,Toys & Games,B01HJDUNRU,https://images-na.ssl-images-amazon.com/images...
633881,toys games learning education early developmen...,NaN,Lewo Wooden Baby Toddler Toys Circle First Bea...,lewo,36248,Toys & Games,B01HJFAGJI,https://images-na.ssl-images-amazon.com/images...
633882,toys games baby toddler toys music sound,NaN,Baby Einstein Take Along Tunes Musical Toy,ba einstein,NaN,Baby,B01HJHA7GI,https://images-na.ssl-images-amazon.com/images...

In [19]:
df_meta.isnull().sum()

category        62243
description     82024
title              21
brand            6847
rank            13851
main_cat         4694
asin                0
imageURL       323987
dtype: int64

In [20]:
df_meta.dtypes

category       object
description    object
title          object
brand          object
rank           object
main_cat       object
asin           object
imageURL       object
dtype: object

In [24]:
df_meta['rank'] = df_meta['rank'].str.replace('>>', '')

In [25]:
df_meta['rank'] = pd.to_numeric(df_meta['rank'])

In [ ]:
# Convert the 'rank' column to a float
# df['rank'] = df['rank'].astype(float)

In [26]:
df_meta.isnull().sum()

category        62243
description     82024
title              21
brand            6847
rank            13852
main_cat         4694
asin                0
imageURL       323987
dtype: int64

In [28]:
df_meta.dtypes

category        object
description     object
title           object
brand           object
rank           float64
main_cat        object
asin            object
imageURL        object
dtype: object

In [29]:
df_meta["category"].fillna(df_meta["category"].mode()[0], inplace=True)
df_meta["description"].fillna(df_meta["description"].mode()[0], inplace=True)
df_meta["brand"].fillna(df_meta["brand"].mode()[0], inplace=True)
df_meta["rank"].fillna(df_meta["rank"].mean(), inplace=True)
df_meta["title"].fillna(df_meta["title"].mode()[0], inplace=True)
df_meta["main_cat"].fillna(df_meta["main_cat"].mode()[0], inplace=True)

In [30]:
df_meta.isnull().sum()

category            0
description         0
title               0
brand               0
rank                0
main_cat            0
asin                0
imageURL       323987
dtype: int64

In [31]:
df_meta.shape

(633883, 8)

In [32]:
df_meta['image_uploaded']=np.nan
df_meta['imageURL']=df_meta['imageURL'].astype(str)
a=0

for i in df_meta['imageURL']:
    z=re.match("^http",i, re.IGNORECASE)
    if bool(z) == True:
        df_meta['image_uploaded'][a]='yes'
    else:
        df_meta['image_uploaded'][a]='no'
    a=a+1

<ipython-input-32-f3fa554ab78b>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_meta['image_uploaded'][a]='yes'

In [33]:
df_meta.drop(columns=['imageURL'],inplace=True)

In [34]:
df_meta.head()

,category,description,title,brand,rank,main_cat,asin,image_uploaded
0,toys games puzzles jigsaw puzzles,three dr suess puzzles green eggs and ham favo...,Dr. Suess 19163 Dr. Seuss Puzzle 3 Pack Bundle,dr seuss,2230717.0,Toys & Games,0000191639,yes
1,toys games action figures statues action figures,b prepare to be afraid b br br the book of be...,Pathfinder: Book of Beasts - Legendary Foes,pathfinder roleplaying jon brazer productions,2294535.0,Toys & Games,0004950763,no
2,toys games action figures statues action figures,,Nursery Rhymes Felt Book,betty lukens,2871983.0,Toys & Games,0005069491,no
3,toys games games card games,blitz vintage card game,Dutch Blitz Card Game,dutch blitz games co,376337.0,Toys & Games,0004983289,no
4,toys games action figures statues action figures,marvel superheroes themed magic ink coloring b...,Magic Pen Painting (Marvel Super Heroes),lee publications,934954.0,Toys & Games,0006466222,no

In [35]:
df_meta.to_csv('meta_toys.csv', index = False)

Review Data set

In [2]:
import pandas as pd

In [3]:
df_rev = pd.read_json('/content/drive/MyDrive/folder/Toys_and_Games.json.gz', orient='columns',lines=True,nrows=200000)
df_rev["reviewTime"] = pd.to_datetime(df_rev["reviewTime"])
df_rev.head()

,overall,vote,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,image,style
0,2,12,False,2016-09-22,A1IDMI31WEANAF,0020232233,Mackenzie Kent,"When it comes to a DM's screen, the space on t...",The fact that 50% of this space is wasted on a...,1474502400,NaN,NaN
1,1,21,False,2016-09-18,A4BCEVVZ4Y3V3,0020232233,Jonathan Christian,An Open Letter to GaleForce9*:\n\nYour unpaint...,Another worthless Dungeon Master's screen from...,1474156800,NaN,NaN
2,3,19,True,2016-09-12,A2EZ9PY1IHHBX0,0020232233,unpreparedtodie,"Nice art, nice printing. Why two panels are f...","pretty, but also pretty useless",1473638400,NaN,NaN
3,5,NaN,True,2017-03-02,A139PXTTC2LGHZ,0020232233,Ashley,Amazing buy! Bought it as a gift for our new d...,Five Stars,1488412800,NaN,NaN
4,1,3,True,2017-02-08,A3IB33V29XIL8O,0020232233,Oghma_EM,As my review of GF9's previous screens these w...,Money trap,1486512000,NaN,NaN

In [4]:
import re
def cleaning(text):
    text = re.sub('[^0-9A-Za-z]+',' ',text)
    text= re.sub('(?<!\w)\d+','',text)
    text=re.sub('-(?!\w)|(?<!\w)-','',text)
    text=text.lower()
    text=re.sub(' +',' ',text)
    return text
df_rev["reviewText"]=df_rev["reviewText"].astype(str)
df_rev["summary"]=df_rev["summary"].astype(str)
df_rev["reviewText"]=df_rev["reviewText"].apply(cleaning)
df_rev["summary"]=df_rev["summary"].apply(cleaning)

In [5]:
df_rev.head()

,overall,vote,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,image,style
0,2,12,False,2016-09-22,A1IDMI31WEANAF,0020232233,Mackenzie Kent,when it comes to a dm s screen the space on th...,the fact that of this space is wasted on art a...,1474502400,NaN,NaN
1,1,21,False,2016-09-18,A4BCEVVZ4Y3V3,0020232233,Jonathan Christian,an open letter to galeforce9 your unpainted mi...,another worthless dungeon master s screen from...,1474156800,NaN,NaN
2,3,19,True,2016-09-12,A2EZ9PY1IHHBX0,0020232233,unpreparedtodie,nice art nice printing why two panels are fill...,pretty but also pretty useless,1473638400,NaN,NaN
3,5,NaN,True,2017-03-02,A139PXTTC2LGHZ,0020232233,Ashley,amazing buy bought it as a gift for our new dm...,five stars,1488412800,NaN,NaN
4,1,3,True,2017-02-08,A3IB33V29XIL8O,0020232233,Oghma_EM,as my review of gf9 s previous screens these w...,money trap,1486512000,NaN,NaN

In [6]:
df_rev["review"] = df_rev['reviewText'].astype(str) +" "+ df_rev["summary"]
df_rev=df_rev.drop(['unixReviewTime','vote','style','image'],axis=1)
df_rev

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,review
0,2,False,2016-09-22,A1IDMI31WEANAF,0020232233,Mackenzie Kent,when it comes to a dm s screen the space on th...,the fact that of this space is wasted on art a...,when it comes to a dm s screen the space on th...
1,1,False,2016-09-18,A4BCEVVZ4Y3V3,0020232233,Jonathan Christian,an open letter to galeforce9 your unpainted mi...,another worthless dungeon master s screen from...,an open letter to galeforce9 your unpainted mi...
2,3,True,2016-09-12,A2EZ9PY1IHHBX0,0020232233,unpreparedtodie,nice art nice printing why two panels are fill...,pretty but also pretty useless,nice art nice printing why two panels are fill...
3,5,True,2017-03-02,A139PXTTC2LGHZ,0020232233,Ashley,amazing buy bought it as a gift for our new dm...,five stars,amazing buy bought it as a gift for our new dm...
4,1,True,2017-02-08,A3IB33V29XIL8O,0020232233,Oghma_EM,as my review of gf9 s previous screens these w...,money trap,as my review of gf9 s previous screens these w...
...,...,...,...,...,...,...,...,...,...
199995,1,False,2006-11-22,A1FVMUTAR3S7NC,B000099ZBM,figuregroundtheory,the heading above pretty much sums it up my ei...,they hurt to wear and serve no purpose,the heading above pretty much sums it up my ei...
199996,4,False,2006-01-11,A3EVO0ZTGQM7UO,B000099ZBM,Jeannie McCarthy,my boys just received this for their birthday ...,my year old twins love this,my boys just received this for their birthday ...
199997,4,True,2005-08-13,A3FA90E7KX99JK,B000099ZBM,Tamela D. Lowery,i ordered this item for my nephew s birthday h...,fun googles,i ordered this item for my nephew s birthday h...
199998,5,False,2005-06-11,A16Q9TAJC8PRTN,B000099ZBM,Francis,this toy is great i really can see up to feet ...,a great spy toy,this toy is great i really can see up to feet ...
199999,4,True,2010-08-11,AYIRKYTTQYZ6U,B000099Z8M,designerflower,this bug watch is unique it was purchased as a...,cool bug watch awesome toy,this bug watch is unique it was purchased as a...

In [7]:
df_rev["Number_of_Words_in_review"] = df_rev["review"].apply(lambda n: len(n.split()))
df_rev

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,review,Number_of_Words_in_review
0,2,False,2016-09-22,A1IDMI31WEANAF,0020232233,Mackenzie Kent,when it comes to a dm s screen the space on th...,the fact that of this space is wasted on art a...,when it comes to a dm s screen the space on th...,95
1,1,False,2016-09-18,A4BCEVVZ4Y3V3,0020232233,Jonathan Christian,an open letter to galeforce9 your unpainted mi...,another worthless dungeon master s screen from...,an open letter to galeforce9 your unpainted mi...,143
2,3,True,2016-09-12,A2EZ9PY1IHHBX0,0020232233,unpreparedtodie,nice art nice printing why two panels are fill...,pretty but also pretty useless,nice art nice printing why two panels are fill...,261
3,5,True,2017-03-02,A139PXTTC2LGHZ,0020232233,Ashley,amazing buy bought it as a gift for our new dm...,five stars,amazing buy bought it as a gift for our new dm...,17
4,1,True,2017-02-08,A3IB33V29XIL8O,0020232233,Oghma_EM,as my review of gf9 s previous screens these w...,money trap,as my review of gf9 s previous screens these w...,28
...,...,...,...,...,...,...,...,...,...,...
199995,1,False,2006-11-22,A1FVMUTAR3S7NC,B000099ZBM,figuregroundtheory,the heading above pretty much sums it up my ei...,they hurt to wear and serve no purpose,the heading above pretty much sums it up my ei...,90
199996,4,False,2006-01-11,A3EVO0ZTGQM7UO,B000099ZBM,Jeannie McCarthy,my boys just received this for their birthday ...,my year old twins love this,my boys just received this for their birthday ...,43
199997,4,True,2005-08-13,A3FA90E7KX99JK,B000099ZBM,Tamela D. Lowery,i ordered this item for my nephew s birthday h...,fun googles,i ordered this item for my nephew s birthday h...,32
199998,5,False,2005-06-11,A16Q9TAJC8PRTN,B000099ZBM,Francis,this toy is great i really can see up to feet ...,a great spy toy,this toy is great i really can see up to feet ...,35
199999,4,True,2010-08-11,AYIRKYTTQYZ6U,B000099Z8M,designerflower,this bug watch is unique it was purchased as a...,cool bug watch awesome toy,this bug watch is unique it was purchased as a...,227

In [8]:
df_rev.isnull().sum()

overall                      0
verified                     0
reviewTime                   0
reviewerID                   0
asin                         0
reviewerName                 8
reviewText                   0
summary                      0
review                       0
Number_of_Words_in_review    0
dtype: int64

In [9]:
df_rev["reviewerName"].fillna(df_rev["reviewerName"].mode()[0], inplace=True)

In [10]:
df_rev.isnull().sum()

overall                      0
verified                     0
reviewTime                   0
reviewerID                   0
asin                         0
reviewerName                 0
reviewText                   0
summary                      0
review                       0
Number_of_Words_in_review    0
dtype: int64

In [11]:
df_rev.shape

(200000, 10)

In [12]:
df_rev['Sentiment']=df_rev['overall']
df_rev['Sentiment'] = df_rev['Sentiment'].replace(5,'positive')
df_rev['Sentiment'] = df_rev['Sentiment'].replace(4,'positive')

df_rev['Sentiment'] = df_rev['Sentiment'].replace(2,'negetive')
df_rev['Sentiment'] = df_rev['Sentiment'].replace(1,'negetive')

df_rev['Sentiment'] = df_rev['Sentiment'].replace(3,'neutral')

In [13]:
df_rev.head()

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,review,Number_of_Words_in_review,Sentiment
0,2,False,2016-09-22,A1IDMI31WEANAF,0020232233,Mackenzie Kent,when it comes to a dm s screen the space on th...,the fact that of this space is wasted on art a...,when it comes to a dm s screen the space on th...,95,negetive
1,1,False,2016-09-18,A4BCEVVZ4Y3V3,0020232233,Jonathan Christian,an open letter to galeforce9 your unpainted mi...,another worthless dungeon master s screen from...,an open letter to galeforce9 your unpainted mi...,143,negetive
2,3,True,2016-09-12,A2EZ9PY1IHHBX0,0020232233,unpreparedtodie,nice art nice printing why two panels are fill...,pretty but also pretty useless,nice art nice printing why two panels are fill...,261,neutral
3,5,True,2017-03-02,A139PXTTC2LGHZ,0020232233,Ashley,amazing buy bought it as a gift for our new dm...,five stars,amazing buy bought it as a gift for our new dm...,17,positive
4,1,True,2017-02-08,A3IB33V29XIL8O,0020232233,Oghma_EM,as my review of gf9 s previous screens these w...,money trap,as my review of gf9 s previous screens these w...,28,negetive

In [14]:
df_rev.to_csv('rev_toys.csv', index = False)

In [15]:
df_meta = pd.read_csv('/content/meta_toys.csv')

merge both file meta and reviw

In [16]:
merged = pd.merge(df_rev,df_meta,on=['asin'], how='inner')
merged.shape

(358435, 18)

In [17]:
merged.drop_duplicates(subset=["reviewText","summary"],keep='first', inplace=True)

In [18]:
merged.shape

(189261, 18)

In [19]:
merged.isnull().sum()

overall                      0
verified                     0
reviewTime                   0
reviewerID                   0
asin                         0
reviewerName                 0
reviewText                   0
summary                      0
review                       0
Number_of_Words_in_review    0
Sentiment                    0
category                     0
description                  0
title                        0
brand                        0
rank                         0
main_cat                     0
image_uploaded               0
dtype: int64

In [20]:
merged.to_csv("Final_Toys_and_Games.csv",index=False)